### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by adamjjones** [adamjjones/assignments#30]
# Key areas of Information to include:

## Contact information
- [ ] Email
- [ ] Phone Number (Google numbers are great if you want to protect your personal number)
- [ ] Github link
- [ ] Portfolio link

## Summary
- [ ] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [ ] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [ ] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [ ] Write where you went college and your degree.
- [ ] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [ ] Upload or submit a link to your resume for review.

**Comment by adamjjones** [comment]
[Adam-Jones-Resume.pdf](https://github.com/adamjjones/assignments/files/3649940/Adam-Jones-Resume.pdf)

**Comment by ktrammell95** [comment]
Oooh, Adam, this looks amazing especially after seeing the really early version you sent me, what a difference! I love the layout and you built out your projects very well.

Don't forget to add your GitHub and LinkedIn links so people can find them also.
